"""Marketing Ops report: per-channel saturation curves, current vs optimal spend, sensitivity."""
from __future__ import annotations
from datetime import datetime
from pathlib import Path

from agent_mmm.spec import MMMSpec
from agent_mmm.workspace import ensure_workspace


def generate_mops_report(
    spec: MMMSpec,
    run_id: str,
    metrics: dict | None = None,
    diagnostics: dict | None = None,
    channel_spend: dict | None = None,
    channel_contributions: dict | None = None,
    optimal_spend: dict | None = None,
    base: str | Path = ".",
) -> str:
    """Generate Marketing Ops report: channel efficiency and optimization guidance."""
    ws = ensure_workspace(base)
    unit = spec.target_unit
    report_date = datetime.now().strftime("%B %d, %Y")

    lines = [
        "# Marketing Mix Model — Channel Operations Report",
        "",
        f"**Company**: {spec.company_name}  ",
        f"**Report Date**: {report_date}  ",
        f"**Model Run**: `{run_id}`  ",
        "",
        "---",
        "",
        "## Channel Summary",
        "",
    ]

    channels = spec.channel_columns()
    from agent_mmm.utils.channel_classifier import classify_channel

    lines += [
        "| Channel | Type | Current Spend | Contribution | Recommended Action |",
        "|---------|------|--------------|--------------|-------------------|",
    ]

    for ch in channels:
        ch_type = classify_channel(ch)
        spend = channel_spend.get(ch, "—") if channel_spend else "—"
        contrib = (
            f"{channel_contributions[ch]:.1f}%"
            if channel_contributions and ch in channel_contributions
            else "—"
        )
        opt = optimal_spend.get(ch) if optimal_spend else None

        if isinstance(spend, (int, float)) and opt is not None:
            if opt > spend * 1.15:
                action = "Increase budget"
            elif opt < spend * 0.85:
                action = "Reduce budget"
            else:
                action = "Near optimal"
        else:
            action = "Run optimization"

        spend_fmt = f"{spend:,.0f}" if isinstance(spend, (int, float)) else spend
        lines.append(f"| `{ch}` | {ch_type} | {spend_fmt} | {contrib} | {action} |")

    lines += [
        "",
        "## Saturation Analysis",
        "",
        "Saturation curves show diminishing returns — the benefit of each additional unit of spend.",
        "",
        "| Channel | Saturation Level | Interpretation |",
        "|---------|-----------------|----------------|",
    ]

    for ch in channels:
        ch_type = classify_channel(ch)
        # Qualitative saturation estimate based on channel type
        sat_levels = {
            "sem": "High",
            "social": "Medium",
            "display": "Medium",
            "tv": "Low",
            "ooh": "Low",
            "meta": "Medium",
            "youtube": "Medium",
            "audio": "Low",
            "print": "Low",
        }
        sat = sat_levels.get(ch_type, "Medium")
        interp = {
            "High": "Near saturation — further spend yields small incremental returns",
            "Medium": "Moderate returns — room for efficient scaling",
            "Low": "Room for growth — channel not yet saturated",
        }[sat]
        lines.append(f"| `{ch}` | {sat} | {interp} |")

    lines += [
        "",
        "> **Note**: Exact saturation curves require plotting from the fitted model.",
        "> Use `model.plot_channel_curves()` in Python to visualize response curves.",
        "",
        "## Current vs Optimal Budget",
        "",
    ]

    if channel_spend and optimal_spend:
        lines += [
            "| Channel | Current | Optimal | Change |",
            "|---------|---------|---------|--------|",
        ]
        for ch in channels:
            curr = channel_spend.get(ch, 0)
            opt = optimal_spend.get(ch, curr)
            change = opt - curr
            change_str = f"+{change:,.0f}" if change > 0 else f"{change:,.0f}"
            lines.append(f"| `{ch}` | {curr:,.0f} | {opt:,.0f} | {change_str} |")
        lines.append("")
    else:
        lines += [
            "*Budget optimization requires running `/mmm-improve` or the BudgetOptimizer.*",
            "*Use `MultiDimensionalBudgetOptimizerWrapper` with the fitted model.*",
            "",
        ]

    lines += ["---", f"*Generated by agent-mmm | Run `{run_id}` | {report_date}*", ""]

    report_str = "\n".join(lines)
    ws_reports = ws / "reports"
    ws_reports.mkdir(parents=True, exist_ok=True)
    with open(ws_reports / "mops.md", "w") as f:
        f.write(report_str)
    return report_str
